version: "2"
services:

  app:
    image: kevineye/wonderland-stats
    build: .
    user: node
    ports:
      - 3000:3000
    command: --server

  dev:
    image: node:16-alpine
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: sh -c 'npm install && npm start'
